/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:224e6113-2a86-4d6a-a1a3-fb534ee56684",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_SVKLLcVsi",
    "aws_user_pools_web_client_id": "7nc82hcq1gu9ke8im75msqmm0d",
    "oauth": {
        "domain": "octankvod9f14ebe3-9f14ebe3-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://localhost/",
        "redirectSignOut": "https://localhost/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://z426eokb5ffopgajrno6dkb5ty.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "ctank-20210624162718-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://dropeiboeeuny.cloudfront.net"
};


export default awsmobile;
